// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwApHt9Bwy-LO71XhdXPaKo9M-KYAt_-0',
    appId: '1:812699627485:android:e6dceded976ae011f19034',
    messagingSenderId: '812699627485',
    projectId: 'nallagram-8067a',
    storageBucket: 'nallagram-8067a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDcc2cZZSkU06y4_nAf1DLnUTPDLKjsEE',
    appId: '1:812699627485:ios:cdc61bb9348b60f1f19034',
    messagingSenderId: '812699627485',
    projectId: 'nallagram-8067a',
    storageBucket: 'nallagram-8067a.appspot.com',
    androidClientId: '812699627485-npbu4v84brti0rmplct6osej0i1ed4ep.apps.googleusercontent.com',
    iosClientId: '812699627485-i1gc7re8608ceqrrdvsfuct2flukls7t.apps.googleusercontent.com',
    iosBundleId: 'com.currently.plusone',
  );
}
